from .course_scraping_service import CourseScrapingService
from .diploma_scraping_service import DiplomaScrapingService
from .idion_course_scraping_service import IdiomCourseScrapingService
from .master_scraping_service import MasterScrapingService
from .seminary_scraping_service import SeminaryScrapingService
from .specialization_scraping_service import SpecializationScrapingService
from .universitary_master_scraping_service import UniversitaryMasterScrapingService
